name: Releaser

on:
  push:
    tags:
      - 'v*'   # only run when a tag starting with "v" is pushed (e.g., v1.0.0)

permissions:
  contents: write   # required for creating GitHub Releases

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required so GoReleaser can access all tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2.12.5
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
